### ISSUE TITLE
Source "extra" parameters from MUSE file

### ISSUE THREAD

**Issue by Virusmater** [melmothx/text-amuse-compile#30]
When calling from a command line It is possible to specify few extra parameters like sitename and siteslogan.
Is it possible to specify those fields somewhere inside of the file? Next to #title, #subtitle and other configurations?

**Comment by melmothx** [comment]
Virusmater ***@***.***> writes:

> When calling from a command line It is possible to specify few extra
> parameters like sitename and siteslogan. Is it possible to specify
> those fields somewhere inside of the file? Next to #title, #subtitle
> and other configurations?

No and yes.

By default, only a few options which are injected in the template are
looked up from the header. They are documented at: 
https://metacpan.org/pod/Text::Amuse::Compile::File#Options-which-are-looked-up-in-the-file-headers-first
and, beside the cover, they are booleans.

This is because the primary compiler usage is from amusewiki, which is a
site, and normally we don't want a text overwriting something like the
site name, slogan, logo, and what not. These are things which are up to
the publisher, not to the published text.

However, if you know what you do, you can resort to a local template, as
documented here:

https://amusewiki.org/library/templates-and-formats#toc3

and have something like this:

[% IF doc.header_defined.sitename %]
[% doc.header_as_latex.sitename %]
[% ELSE %]
[% safe_options.sitename %]
[% END %]

Instead of the default, which is using safe_options.siteslogan and
safe_options.sitename

You'll need to call the compiler with --ttdir, though.

The problem with this approach is that the default template changes from
time to time, and even if we try to be backcompatible, sometimes changes
can't be avoided, you may miss new options, etc.

Does it help?

-- 
Marco

**Comment by melmothx** [comment]
Assuming question was answered, closing.
